apiVersion: v1
kind: Service
metadata:
  name: upload-api
  namespace: dmz
  labels:
    app.kubernetes.io/name: upload-api
    app.kubernetes.io/component: api
    zone: dmz
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: upload-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
