apiVersion: v1
kind: Service
metadata:
  name: integration-hub
  namespace: processing
  labels:
    app.kubernetes.io/name: integration-hub
    app.kubernetes.io/component: integration
    zone: processing
spec:
  selector:
    app.kubernetes.io/name: integration-hub
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
